---
# Source: products/charts/products/templates/service-account.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: products-service-account 
  namespace: ecommerce
---
# Source: products/charts/products/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: products-service
  namespace: ecommerce
spec:
  selector:
    app: products
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 8004
    targetPort: 8004
---
# Source: products/charts/products/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: products
  namespace: ecommerce
spec:
  replicas: 1
  selector:
    matchLabels:
      app: products
      role: api
      workload: ecommerce
  template:
    metadata:
      labels:
        app: products
        role: api
        workload: ecommerce
    spec:
      serviceAccountName: products-service-account
      topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: "topology.kubernetes.io/zone"
        whenUnsatisfiable: DoNotSchedule
        labelSelector:
          matchLabels:
            app: products
      nodeSelector:
        managedBy: karpenter
      containers:
      - name: envoy
        image: envoyproxy/envoy:v1.25.7
        imagePullPolicy: Always
        args: ["-l", "debug", "--local-address-ip-version", "v4", "-c", "/run/envoy/envoy.yaml", "--base-id", "2"]
        ports:
        - containerPort: 8004
        volumeMounts:
        - name: envoy-config
          mountPath: "/run/envoy"
          readOnly: true 
        - name: spire-agent-socket
          mountPath: /run/spire/sockets
          readOnly: true
      - name: products-container
        image: "lukondefmwila/ecommerce-products:0.1.5"
        ports:
        - containerPort: 3004
        resources:
          requests:
            cpu: "1"
            memory: "64Mi"
      volumes:
      - name: envoy-config
        configMap:
          name: products-envoy-config
      - name: spire-agent-socket
        hostPath:
          path: /run/spire/sockets
          type: DirectoryOrCreate
