apiVersion: v1
kind: ConfigMap
metadata:
  name: edge-envoy-config
  namespace: ecommerce
data:
  envoy.yaml: |
    node:
      id: "edge"
      cluster: "ecommerce-spire-cluster"
    static_resources:
      listeners:
      - name: service_proxy
        address:
          socket_address: { address: 0.0.0.0, port_value: 8081 }
        filter_chains:
        - filters:
          - name: envoy.filters.network.http_connection_manager
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
              common_http_protocol_options:
                idle_timeout: 1s
              codec_type: AUTO
              stat_prefix: ingress_http
              route_config:
                virtual_hosts:
                - name: service_proxy
                  domains: ["*"]
                  routes:
                  - match: { prefix: "/v1/graphql" }
                    route: { cluster: graphql }
                  - match: { prefix: "/v1/orders" }
                    route: { cluster: orders }
                  - match: { prefix: "/v1/products" }
                    route: { cluster: products }
              http_filters:
              - name: envoy.filters.http.router
                typed_config:
                  "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
          transport_socket:
            name: envoy.transport_sockets.tls
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.DownstreamTlsContext
              common_tls_context:
                tls_certificate_sds_secret_configs:
                - name: "spiffe://outlier.org/ns/ecommerce/sa/edge-proxy-service-account"
                  sds_config:
                    resource_api_version: V3
                    api_config_source:
                      api_type: GRPC
                      transport_api_version: V3
                      grpc_services:
                        envoy_grpc:
                          cluster_name: spire_agent
                tls_params:
                  ecdh_curves:
                    - X25519:P-256:P-521:P-384
      clusters:
      - name: spire_agent
        connect_timeout: 0.25s
        http2_protocol_options: {}
        load_assignment:	
          cluster_name: spire_agent
          endpoints:	
          - lb_endpoints:	
            - endpoint:	
                address:	
                  pipe:	
                    path: /run/spire/sockets/agent.sock
      - name: graphql
        connect_timeout: 1s
        type: STRICT_DNS
        load_assignment:
          cluster_name: graphql
          endpoints:
          - lb_endpoints:
            - endpoint:
                address:
                  socket_address:
                    address: graphql-service.ecommerce.svc.cluster.local
                    port_value: 8002
        transport_socket:
            name: envoy.transport_sockets.tls
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.UpstreamTlsContext
              common_tls_context:
                tls_certificate_sds_secret_configs:
                - name: "spiffe://outlier.org/ns/ecommerce/sa/edge-proxy-service-account"
                  sds_config:
                    resource_api_version: V3
                    api_config_source:
                      api_type: GRPC
                      transport_api_version: V3
                      grpc_services:
                        envoy_grpc:
                          cluster_name: spire_agent
                combined_validation_context:
                  # validate the SPIFFE ID of upstream server
                  default_validation_context:
                    match_typed_subject_alt_names:
                    - san_type: URI
                      matcher:
                        exact: "spiffe://outlier.org/ns/ecommerce/sa/graphql-service-account"
                  validation_context_sds_secret_config:
                    name: "spiffe://outlier.org"
                    sds_config:
                      resource_api_version: V3
                      api_config_source:
                        api_type: GRPC
                        transport_api_version: V3
                        grpc_services:
                          envoy_grpc:
                            cluster_name: spire_agent
                tls_params:
                  ecdh_curves:
                    - X25519:P-256:P-521:P-384
      - name: orders
        connect_timeout: 1s
        type: STRICT_DNS
        load_assignment:
          cluster_name: orders
          endpoints:
          - lb_endpoints:
            - endpoint:
                address:
                  socket_address:
                    address: orders-service.ecommerce.svc.cluster.local
                    port_value: 8003
        transport_socket:
            name: envoy.transport_sockets.tls
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.UpstreamTlsContext
              common_tls_context:
                tls_certificate_sds_secret_configs:
                - name: "spiffe://outlier.org/ns/ecommerce/sa/edge-proxy-service-account"
                  sds_config:
                    resource_api_version: V3
                    api_config_source:
                      api_type: GRPC
                      transport_api_version: V3
                      grpc_services:
                        envoy_grpc:
                          cluster_name: spire_agent
                combined_validation_context:
                  # validate the SPIFFE ID of upstream server
                  default_validation_context:
                    match_typed_subject_alt_names:
                    - san_type: URI
                      matcher:
                        exact: "spiffe://outlier.org/ns/ecommerce/sa/orders-service-account"
                  validation_context_sds_secret_config:
                    name: "spiffe://outlier.org"
                    sds_config:
                      resource_api_version: V3
                      api_config_source:
                        api_type: GRPC
                        transport_api_version: V3
                        grpc_services:
                          envoy_grpc:
                            cluster_name: spire_agent
                tls_params:
                  ecdh_curves:
                    - X25519:P-256:P-521:P-384
      - name: products
        connect_timeout: 1s
        type: STRICT_DNS
        load_assignment:
          cluster_name: products
          endpoints:
          - lb_endpoints:
            - endpoint:
                address:
                  socket_address:
                    address: products-service.ecommerce.svc.cluster.local
                    port_value: 8004
        transport_socket:
            name: envoy.transport_sockets.tls
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.UpstreamTlsContext
              common_tls_context:
                tls_certificate_sds_secret_configs:
                - name: "spiffe://outlier.org/ns/ecommerce/sa/edge-proxy-service-account"
                  sds_config:
                    resource_api_version: V3
                    api_config_source:
                      api_type: GRPC
                      transport_api_version: V3
                      grpc_services:
                        envoy_grpc:
                          cluster_name: spire_agent
                combined_validation_context:
                  # validate the SPIFFE ID of upstream server
                  default_validation_context:
                    match_typed_subject_alt_names:
                    - san_type: URI
                      matcher:
                        exact: "spiffe://outlier.org/ns/ecommerce/sa/products-service-account"
                  validation_context_sds_secret_config:
                    name: "spiffe://outlier.org"
                    sds_config:
                      resource_api_version: V3
                      api_config_source:
                        api_type: GRPC
                        transport_api_version: V3
                        grpc_services:
                          envoy_grpc:
                            cluster_name: spire_agent
                tls_params:
                  ecdh_curves:
                    - X25519:P-256:P-521:P-384