apiVersion: v1
kind: ServiceAccount
metadata:
  name: edge-proxy-service-account 
  namespace: ecommerce
---
apiVersion: v1
kind: Service
metadata:
  name: edge-proxy
  namespace: ecommerce
spec:
  selector:
    app: edge-proxy
  type: LoadBalancer
  ports:
  - protocol: TCP
    name: service-proxy-listener
    port: 8080
    targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: edge-proxy
  namespace: ecommerce
spec:
  replicas: 1
  selector:
    matchLabels:
      app: edge-proxy
      workload: ecommerce
  template:
    metadata:
      labels:
        app: edge-proxy
        workload: ecommerce
    spec:
      serviceAccountName: edge-proxy-service-account
      nodeSelector:
        managedBy: karpenter
      containers:
      - name: envoy
        image: envoyproxy/envoy:v1.25.7
        imagePullPolicy: Always
        args: ["-l", "debug", "--local-address-ip-version", "v4", "-c", "/run/envoy/envoy.yaml", "--base-id", "2"]
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: envoy-config
          mountPath: "/run/envoy"
          readOnly: true 
        - name: spire-agent-socket
          mountPath: /run/spire/sockets
          readOnly: true
      volumes:
      - name: envoy-config
        configMap:
          name: edge-envoy-config
      - name: spire-agent-socket
        hostPath:
          path: /run/spire/sockets
          type: DirectoryOrCreate